services:
  simple-cv-nginx:
    container_name: simple-cv-nginx
    mem_limit: 128m
    build:
      context: docker/
      dockerfile: nginx.docker
    platform: linux/amd64
    restart: always
    depends_on:
      - simple-cv-postgres
      - simple-cv-nestjs
    volumes:
      - ./:/app
      - ./var/logs/nginx:/var/log/nginx
      - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf:ro
      - uploads:/app/src/uploads
    ports:
      - "1090:80"
    networks:
      simple-cv-network:
        aliases:
          - simple-cv-nestjs

  simple-cv-nestjs:
    container_name: simple-cv-nestjs
    mem_limit: 1024m
    build:
      context: .
      dockerfile: docker/node.docker
    restart: always
    working_dir: /app/src/simple-cv-api
    volumes:
      - ./:/app
      - uploads:/app/src/uploads
    ports:
      - "1091:9229"
    networks:
      - simple-cv-network
    depends_on:
      - simple-cv-postgres
    command: sh -c "yarn install && yarn start:debug"

  simple-cv-postgres:
    container_name: simple-cv-postgres
    mem_limit: 1024m
    image: postgres:17.6
    restart: always
    environment:
      POSTGRES_DB: simple_cv_test
      POSTGRES_USER: simple_cv_user_test
      POSTGRES_PASSWORD: 123456_test
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./var/logs/postgres:/var/lib/postgresql/data/log
    ports:
      - "1092:5432"
    networks:
      - simple-cv-network
    command:
      - postgres
      - -c
      - log_min_duration_statement=0
      - -c
      - log_directory=log
      - -c
      - logging_collector=on

volumes:
  postgres_data:
  uploads:

networks:
  simple-cv-network:
    driver: bridge