networks:
  simple-cv-network:
    driver: bridge

services:
  nginx:
    mem_limit: 1024m
    build:
      context: docker/
      dockerfile: nginx.docker
    platform: linux/amd64
    restart: always
    depends_on:
      - nestjs
    volumes:
      - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "1090:80"
    networks:
      - simple-cv-network

  nestjs:
    build:
      context: .
      dockerfile: docker/node.docker
    container_name: nestjs
    restart: always
    working_dir: /app/src/simple-cv-api
    volumes:
       - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf:ro
       - ./:/app
    ports:
      - "9229:9229"
    networks:
      - simple-cv-network
    command: sh -c "yarn start:debug"
