networks:
  simple-cv-network:
    driver: bridge

services:
  nginx:
    mem_limit: 1024m
    build:
      context: docker/
      dockerfile: nginx.docker
    platform: linux/amd64
    restart: always
    depends_on:
      - nestjs
    volumes:
      - ./:/app
      - ./var/logs/nginx:/var/log/nginx
    ports:
      - "1090:80"
    networks:
      - simple-cv-network

  nestjs:
    build:
      context: .
      dockerfile: docker/node.prod.docker
    container_name: nestjs
    restart: always
    working_dir: /app/src/simple-cv-api
    networks:
      - simple-cv-network
