networks:
  simple-cv-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.254

services:
  nginx:
    mem_limit: 1024m
    build:
      context: docker/
      dockerfile: nginx.docker
    platform: linux/amd64
    restart: always
    depends_on:
      - nestjs
    volumes:
      - ./var/logs/nginx:/var/log/nginx
    ports:
      - "1090:80"
    networks:
      - simple-cv-network

  nestjs:
    build:
      context: .
      dockerfile: docker/node.docker
    container_name: nestjs
    restart: always
    working_dir: /app/src/simple-cv-api
    volumes:
      - ./:/app
    networks:
      - simple-cv-network
    command: sh -c "yarn build && node dist/main.js"
