services:
  simple-cv-nginx:
    container_name: simple-cv-nginx
    mem_limit: 128m
    build:
      context: docker/
      dockerfile: nginx.docker
    platform: linux/amd64
    restart: always
    depends_on:
      - simple-cv-postgres
      - simple-cv-nestjs
    volumes:
      - ./:/app
      - ./var/logs/nginx:/var/log/nginx
      - uploads:/app/src/uploads
    ports:
      - "1090:80"
    networks:
      - simple-cv-network

  simple-cv-nestjs:
    container_name: simple-cv-nestjs
    mem_limit: 1024m
    build:
      context: .
      dockerfile: docker/node.prod.docker
    restart: always
    working_dir: /app/src/simple-cv-api
    depends_on:
      - simple-cv-postgres
    volumes:
      - uploads:/app/src/uploads
    networks:
      - simple-cv-network
    
  simple-cv-postgres:
    container_name: simple-cv-postgres
    mem_limit: 1024m
    image: postgres:17.6
    restart: always
    environment:
      POSTGRES_DB: simple_cv
      POSTGRES_USER: simple_cv_user
      POSTGRES_PASSWORD: SoeeKKDs432_4pod446
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "1092:5432"
    networks:
      - simple-cv-network

volumes:
  postgres_data:
  uploads:

networks:
  simple-cv-network:
    driver: bridge
