server {
    listen 80;
    server_name simple-cv.life;

    root        /app/src/simple-cv.life;
    index       index.html;

    access_log  /var/log/nginx/simple-cv-access.log;
    error_log   /var/log/nginx/simple-cv-error.log;

    location ~ /\.(ht|svn|git) {
       deny all;
    }
}
